### ISSUE TITLE
does not work on Windows

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [foxylion/gwt-build#1]
Tried to run on Windows. It downloaded the VM ok, but once I tried to run the Docker container:
```vagrant@vagrant-ubuntu-trusty-64:/vagrant$ docker run --rm -v `pwd`:/gwt foxyli
on/gwt-build ant clean dist-dev
Unable to find image 'foxylion/gwt-build:latest' locally
docker: Error response from daemon: manifest for foxylion/gwt-build:latest not found.
See 'docker run --help'.```

**Comment by foxylion** [comment]
Hi @OlliTietavainenVaadin ,
I'm sorry, the image should now be available again.
